name: jh_class
channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- tensorflow=2.15.0
- pandas=2.2.0
- matplotlib=3.8.3
- ipython=8.21.0
- transformers=4.37.2
- jupyter=1.0.0
- sentencepiece=0.1.99
- click=8.0.4
- imageio
- keras-preprocessing
- pydot

