# conda env create -f environment.yml
# conda info --envs
# conda remove -n ENVNAME --all


name: pt2
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1



  # - conda-forge::numpy=1.21.*
  # - nodejs=16.13.*

  # - pip
  # - pip:
  #   - Flask-Testing