# conda env create -f environment.yml
# conda info --envs
# conda remove -n ENVNAME --all


name: kd5
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm


  # - bokeh=2.4.2
  # - conda-forge::numpy=1.21.*
  # - nodejs=16.13.*
  # - flask
  # - pip
  # - pip:
  #   - Flask-Testing